### ISSUE TITLE
docker makemigrations ends on "nonexistent parent node" error

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#82]
# Summary

Running the install with docker process from scratch on the genomics_backend branch, the makemigration step returns an "nonexistent parent node" error.

# Bug full description

> docker-compose run --rm backend sh -c "python manage.py makemigrations"
> […]
> Migration clin_overview.0003_clinicaldata_time_series dependencies reference nonexistent parent node ('clin_overview', '0002_alter_clinicaldata_cud_current_treatment_phase')

# Steps to reproduce

1. docker-compose build
2. docker-compose run --rm backend sh -c "python manage.py makemigrations"

# Logs

> docker-compose run --rm backend sh -c "python manage.py makemigrations"
> WARN[0000] The "UID" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "GID" variable is not set. Defaulting to a blank string. 
> Traceback (most recent call last):
>   File "manage.py", line 22, in <module>
>     main()
>   File "manage.py", line 18, in main
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 89, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 88, in handle
>     loader = MigrationLoader(None, ignore_no_migrations=True)
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 53, in __init__
>     self.build_graph()
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 259, in build_graph
>     self.graph.validate_consistency()
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
>     [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
>     [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/graph.py", line 58, in raise_error
>     raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
> django.db.migrations.exceptions.NodeNotFoundError: Migration clin_overview.0003_clinicaldata_time_series dependencies reference nonexistent parent node ('clin_overview', '0002_alter_clinicaldata_cud_current_treatment_phase')

# Environment

 - Oncodash Version: genomics_backend / 4485fef
 - OS: Ubuntu 22

For developers:
 - Docker version: 23.0.6, build ef23cbc
 - Docker-compose version: v2.0.1

**Comment by jdreo** [comment]
Solution: purge all migrations, cache files and DB:
`
find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
find . -path "*/migrations/*.pyc"  -delete
del db.sqlite3
`
